### ISSUE TITLE
Incorrect parent boeing-wave4-eroteme/notification-service/pom.xml

### ISSUE THREAD

**Issue by sushmitha007** [stackroute/boeing-wave4-eroteme#47]
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.3.RELEASE</version>
		<relativePath/> 
	</parent>

**Comment by Udayuthukota** [comment]
versions are removed  in pom
